#### Name: Chinedu Emmanuel Onyeka
#### Course: DATA1200 - Assignment4
#### Date: November 21st, 2021

In [1]:
# Load Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
url = "https://raw.githubusercontent.com/chinedu2301/DC_Analytics/main/drugdataset.csv"
drug = pd.read_csv(url)
drug.head(n = 10)

Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    1   2            1   25.355  drugY
1   47    0   1            1   13.093  drugC
2   47    0   1            1   10.114  drugC
3   28    1   0            1    7.798  drugX
4   61    1   1            1   18.043  drugY
5   22    1   0            1    8.607  drugX
6   49    1   0            1   16.275  drugY
7   41    0   1            1   11.037  drugC
8   60    0   0            1   15.171  drugY
9   43    0   1            0   19.368  drugY

In [3]:
# Identify unique types of Drug
drug['Drug'].unique()

array(['drugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [4]:
# Check the summary statistics
drug.describe().T

count       mean        std     min      25%      50%    75%  \
Age          200.0  44.315000  16.544315  15.000  31.0000  45.0000  58.00   
Sex          200.0   0.480000   0.500854   0.000   0.0000   0.0000   1.00   
BP           200.0   1.090000   0.821752   0.000   0.0000   1.0000   2.00   
Cholesterol  200.0   0.515000   0.501029   0.000   0.0000   1.0000   1.00   
Na_to_K      200.0  16.084485   7.223956   6.269  10.4455  13.9365  19.38   

                max  
Age          74.000  
Sex           1.000  
BP            2.000  
Cholesterol   1.000  
Na_to_K      38.247

In [5]:
# Create x and y variables
X = drug.drop('Drug', axis = 1).to_numpy()
y = drug['Drug'].to_numpy()

# Create Train and Test datasets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify = y, test_size = 0.20, random_state = 101)

# Scale the data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train2 = sc.fit_transform(X_train)
x_test2 = sc.transform(X_test)

In [6]:
#Script for SVM and NB
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix  

for name,method in [('SVM', SVC(kernel='linear',random_state=100)),
                    ('Naive Bayes',GaussianNB())]: 
    method.fit(x_train2,y_train)
    predict = method.predict(x_test2)
    target_names=['drugA', 'drugB', 'drugC', 'drugX', 'drugY']
    print('\nEstimator: {}'.format(name)) 
    print(confusion_matrix(y_test,predict))  
    print(classification_report(y_test,predict,target_names=target_names))


Estimator: SVM
[[ 5  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  1 17]]
              precision    recall  f1-score   support

       drugA       1.00      1.00      1.00         5
       drugB       1.00      1.00      1.00         3
       drugC       1.00      1.00      1.00         3
       drugX       0.92      1.00      0.96        11
       drugY       1.00      0.94      0.97        18

    accuracy                           0.97        40
   macro avg       0.98      0.99      0.99        40
weighted avg       0.98      0.97      0.98        40


Estimator: Naive Bayes
[[ 5  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0 11  0]
 [ 1  0  3  2 12]]
              precision    recall  f1-score   support

       drugA       0.83      1.00      0.91         5
       drugB       1.00      1.00      1.00         3
       drugC       0.50      1.00      0.67         3
       drugX       0.85      1.00      0.92        11
       drugY      